import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import styled from "styled-components";

const inter = Inter({ subsets: ["latin"] });

const First = styled.div`
  border: 1px solid red;
  height: 40px;
  width: 450px;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <First>
          <p>this is how font family added</p>
        </First>
      </main>
    </>
  );
}
